title: Romantick
baseurl: /
permalink: '/:title/'
layout_style: list
palette: green
header:
  has_nav: true
  logo_img: ''
  title: Romantick
footer:
  content: '&copy; All rights reserved. rtest'
  has_social: true
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
